# Generated by Django 5.2 on 2025-04-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_category_image_url_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Sản phẩm nổi bật'),
        ),
    ]
